### ISSUE TITLE
Any Plans To Ship ARM Images?

### ISSUE THREAD

**Issue by vkhitrin** [hugomods/docker#33]
Hey,

Are you also planning to ship `arm64` images? Right now, all images are built for the `amd64` architecture.
This a nitpick, but it would be nice to have.

Manually building the images work, but I was curious if there are any limitations to building `arm64` in CI (for example, I don't know the constraints of CI/CD minutes for this project).

```bash
podman run --rm -it quay.io/vkhitrin/hugo:reg-base
hugo v0.112.3 linux/arm64 BuildDate=unknown
GOOS="linux"
GOARCH="arm64"
GOVERSION="go1.20.4"
```

**Comment by razonyang** [comment]
Hi, I don't know where should I to start, I want to know more about this before setting about implementing it, so that I can test and confirm whether the `arm64` images work. It would be helpful if there are references/docs about this.

PR are also welcome.

> I don't know the constraints of CI/CD minutes for this project.

As I know, it's unlimited for public repositories.

> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions

**Comment by vkhitrin** [comment]
Hi, @razonyang,

> Hi, I don't know where should I to start, I want to know more about this before setting about implementing it, so that I can test and confirm whether the `arm64` images work. It would be helpful if there are references/docs about this.

There is a guide provided by Docker: https://docs.docker.com/build/ci/github-actions/multi-platform/
It is part of their GitHub action: https://github.com/docker/build-push-action#customizing

> 
> PR are also welcome.

I will try to propose a PR for this.

> 
> > I don't know the constraints of CI/CD minutes for this project.
> 
> As I know, it's unlimited for public repositories.
> 
> > GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions

You are right. Their public runners should be free for all.

**Comment by vkhitrin** [comment]
@razonyang, sorry for the delay. I was not able to follow up in a timely manner 😢.

Thank you for shipping ARM images!
