### ISSUE TITLE
I cant start when I use "hugo-theme-next" theme

### ISSUE THREAD

**Issue by OnqiauJliu** [hugomods/docker#48]
My english not very well, I've asked the question in both Chinese and English, so if you reply in either, I'd be happy to translate!

I was using klakegg/hugo:latest-ext image and hugo-theme-next theme before and everything worked fine.  After that using hugomods/hugo image does not start properly.  I tried latest and exts tags and get the same error log, what should I do?

我之前使用klakegg/hugo:latest-ext镜像和hugo-theme-next主题一切正常。之后使用hugomods/hugo镜像无法正常启动。我试过latest和exts标签，得到相同的报错日志，我应该做些什么？

This is error log:
```
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/src/server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.4.0
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/src/server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.4.0
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/src/server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.4.0
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/src/server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.4.0
```

**Comment by razonyang** [comment]
方便提供你的站点仓库复现问题吗？

但从错误信息来看，是缺少了某些模块，但不清楚具体是什么依赖。

**Comment by razonyang** [comment]
刚测试了下 next 的入门模板，并没有问题，如果可以，麻烦提供下复现的仓库和使用的 Docker 命令。

![image](https://github.com/hugomods/docker/assets/17720932/3fa70301-4a87-48f6-b825-b3c84f156692)

![image](https://github.com/hugomods/docker/assets/17720932/0c3adeaa-0e8c-4864-86e4-2ccf9b6ad4b5)

**Comment by OnqiauJliu** [comment]
> 刚测试了下 next 的入门模板，并没有问题，如果可以，麻烦提供下复现的仓库和使用的 Docker 命令。
> 
> ![image](https://user-images.githubusercontent.com/17720932/256318633-3fa70301-4a87-48f6-b825-b3c84f156692.png)
> 
> ![image](https://user-images.githubusercontent.com/17720932/256318571-0c3adeaa-0e8c-4864-86e4-2ccf9b6ad4b5.png)

我创建了一个新的目录hugo-test， 执行`sudo docker run -it --rm -v /home/admin/hugo-test:/src hugomods/hugo:exts npm i` 报错， 日志如下：
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /src/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/src/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-26T19_58_40_748Z-debug-0.log
```

执行 `sudo docker run -it --rm -v /home/admin/hugo-test:/src --user 1000:1000 hugomods/hugo:exts new site .` 同样无法启动镜像， 报错日志：
```
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/src/new'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.4.0
```

**Comment by razonyang** [comment]
`npm i` 是可选的，与你所使用的主题有关，粗略看了下，Next 应该不使用 NPM，可忽略。

这个问题的原因是你使用了原本 `klakegg/hugo` 自行创建的映射命令，比如 `server` 对应 `hugo server`，`new` 对应 `hugo new`，而 `hugomods/hugo` 仅包含原本的 `hugo` 命令，不对其做任何映射。
对此，你只需要使用原本 `hugo` 的命令即可，比如：

```sh
 sudo docker run -it --rm -p 1234:1234 -v ${PWD}:/src --user 1000:1000 hugomods/hugo:exts hugo server -p 1234 --bind 0.0.0.0
```

> 端口 `1234` （三处）可替换为任意合理端口。
> `--bind 0.0.0.0` 是必要的。
