### ISSUE TITLE
Unsure if this is a bug: Is gcc needed at runtime for hugo extended?

### ISSUE THREAD

**Issue by xuhdev** [hugomods/docker#69]
I saw that `gcc` is installed on an image with hugo extended: https://github.com/hugomods/docker/blob/fc7652a36b00009c67b751c48b15a213c5144a17/docker/hugo/snippets/common#L4

Is this really needed at runtime? I don't see anywhere in hugo's doc that says so.

**Comment by razonyang** [comment]
> Is this really needed at runtime? I don't see anywhere in hugo's doc that says so.

`gcc` is required to build Hugo extended version, but it seems a legacy issue of [refactoring](https://github.com/hugomods/docker/commit/4204ca78d675a40a79a196cf1cc10701e96c776a).

**Comment by razonyang** [comment]
I created a PR #70, but tests fails, it's required.

https://github.com/hugomods/docker/actions/runs/8532254522/job/23373120321?pr=70
https://github.com/hugomods/docker/actions/runs/8532254522/job/23373120504?pr=70
https://github.com/hugomods/docker/actions/runs/8532254522/job/23373120645?pr=70
https://github.com/hugomods/docker/actions/runs/8532254522/job/23373121324?pr=70
