### ISSUE TITLE
Documentation for creating a new site

### ISSUE THREAD

**Issue by iangozer** [hugomods/docker#72]
Not sure if I missed something but in following the documentation I get errors "Error: command error: Unable to locate config file or config directory. Perhaps you need to create a new site."

From what I have pieced together from other guides I needed to:
`docker run --rm -v $(pwd):/src hugomods/hugo:exts hugo new site new_site --format yaml`
`sudo chown -R $USER: new_site`
`cd new_site`

before creating the docker compose. Sure it would help others to know this (if correct) in the docs

**Comment by razonyang** [comment]
Yeah, there isn't doc about creating site, will update doc later.

**Comment by razonyang** [comment]
Done, https://docker.hugomods.com/docs/development/prerequisite/#hugo-site, thanks for your feedback.
