### ISSUE TITLE
Issue with image size and tags

### ISSUE THREAD

**Issue by NicolasCARPi** [hugomods/docker#94]
Hello,

The default tag for `hugomods/hugo` is **ten times** bigger than the previous `klakegg` one:

~~~bash
$ docker images | grep hugo
hugomods/hugo                             latest               a27ad65b7f43   2 days ago      523MB
klakegg/hugo                              0.93.2               f526a752cf0e   2 years ago     51.5MB
~~~

The documentation describes this image as **Minimal** as a first adjective. Still, it seems the `latest` tags contains way more than just the hugo bin. I also could not find any clear list of the tags and what they correspond to.

The doc says: "We offer a wide range of images variants to suit your requirements, such as extended version, Git, Go, Node.js, NPM, Yarn, Dart Sass etc."

But it doesn't explain which tags to use and why they exist in the first place.

IMHO the default tag, `latest` should be a barebone hugo binary, and not contain npm/yarn and such.

The split in many little files of the Dockerfile makes it a bit hard to understand what is really happening, too.

Cheers,
~Nicolas

**Comment by razonyang** [comment]
In short, you need to use `base` or `std-base` tag, please check out https://docker.hugomods.com/docs/tags/ for details.

> IMHO the default tag, latest should be a barebone hugo binary, and not contain npm/yarn and such.

It's should be consider as a historical reason, and as to the backwards compatibility, this won't be changed.

**Comment by NicolasCARPi** [comment]
I understand, thank you!

In the meantime, I went with a different path, which is fetching the hugo bin from github, and copying it to a `scratch` image, along with the site.

**Comment by razonyang** [comment]
> I  went with a different path, which is fetching the hugo bin from github, and copying it to a scratch image

Yeah, it's a good way to keep image as small as possible if you don't need some package manager.

Btw, you may need to update ca-certificates in some way if your site need to request external resources (i.e. `getRemote`).

**Comment by NicolasCARPi** [comment]
> if you don't need some package manager.

I do, but that's in another "builder" image, then I copy the webpacked css/js into the final image. Final image is 126 Mb.

> you may need to update ca-certificates in some way

Thanks for the info, but it doesn't request any external thing, so that works for me.
